config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'group#index'

  resources :entity, only: %i[new create]
  resources :group, only: %i[index show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :entity_groups, dependent: :destroy
  has_and_belongs_to_many :groups, join_table: 'entity_groups', dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/entity_group.rb
class EntityGroup < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :icon
  has_many :entity_groups, dependent: :destroy
  has_and_belongs_to_many :entities, join_table: 'entity_groups'

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :entities, foreign_key: :author_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/entity_controller.rb
class EntityController < ApplicationController
  before_action :authenticate_user!
  def new
    @pagename = 'NEW TRANSACTION'
    @categories = Group.all
  end

  def create
    @pagename = 'NEW TRANSACTION'
    @entity = Entity.new(name: params[:name], amount: params[:amount])
    @entity.author = current_user
    @entity.save
    @groups = params[:category]
    @groups.each do |category|
      @entity_groups = EntityGroup.new(entity: @entity, group: Group.find(category))
      puts @entity_groups.errors.messages unless @entity_groups.save
    end
    if @entity.save
      redirect_to group_index_path, notice: 'Saved new transaction'
    else
      @entity.errors.full_messages
    end
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, :category[])
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups = Group.order(created_at: :desc)
    @amounts = Entity.joins(:groups)
      .group('groups.id')
      .select('groups.id as group_id, sum(entities.amount) as total_amount')
    @pagename = 'TRANSACTION'
  end

  def show
    @group = Group.find(params[:id])
    @entities = EntityGroup.includes(:entity).where(group: @group).order(created_at: :desc)
    @pagename = 'DETAIL'
  end

  def new
    @pagename = 'NEW CATEGORY'
    @group = Group.new
  end

  def create
    @pagename = 'NEW CATEGORY'
    @group = Group.new(name: params[:name], icon: params[:icon])
    @group.icon.attach(params[:group][:icon])
    if @group.save
      redirect_to group_index_path, notice: 'Saved new category'
    else
      @group.errors.full_messages
    end
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entity_helper.rb
module EntityHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/entity/new.html.erb
<%=render partial: "shared/sub_navbar", locals: {pagename: @pagename, link: 'back'}%>
<div class="container-fluid">
<%= form_with model: @entity, url:  entity_index_path(params[:id]), method: :post do |f| %>

<div class="d-flex justify-content-between align-items-center">
<h1 class="h3">Add New Transaction</h1>
<%= link_to "Add New Category",  new_group_path, class: "btn btn-success" %>
</div>

<div class="form-group">
<div class="form-inline mb-3">
     <%= f.label :name, class: "form-label mr-3" do %>
       Name
       <input type="text" name="name" class= "form-control">
     <%end%>
  </div>
  <div class="form-inline mb-3">
     <%= f.label :amount, class: "form-label mr-3" do %>
       Amount
       <input type="number" name="amount" min="0" step="0.1" class= "form-control">
     <%end%>
  </div>
<%@categories.each do |category|%>
 
  <div class="form-inline mb-3">
 <%= f.label :category, class: "form-check-label mr-3" do %>
    <input type="checkbox" name="category[]" value="<%=category.id%>">
  <%=category.name%>
  <%end%>
  </div>

<%end%>

<%= f.submit "Add Transaction", class: "btn btn-primary" %>
<% end %>

</div>

app/views/entity/show.html.erb
<%=render partial: "shared/sub_navbar", locals: {pagename: @pagename}%>
<div class="entity-show d-flex flex-column">
<div class="entity-show-top d-flex">
<div class="img-container d-flex">
<%@icons.each do |image|%>
<%= image_tag url_for(image.group.icon.variant(resize_to_limit: [100/@icons.length, 100/@icons.length])), class: "logo_photo" unless @icons.empty?%>
<%end%>
</div>
<p><%=@entity.name%></p>
</div>
<p>Commodi minima excepturi repudiandae velit hic maxime
doloremque. Quaerat provident commodi consectetur veniam similique ad 
earum omnis ipsum saepe, voluptas, hic voluptates pariatur est explicabo 
fugiat, dolorum eligendi quam cupiditate excepturi mollitia maiores labore 
suscipit quas? Nulla, placeat.</p>
<hr>
<h1>Transaction <%=@entity.id%></h1>
<p><%=@entity.created_at.strftime("%d %b %Y")%></p>
<hr>
<div class="d-flex justify-content-between">
<p class="total-heading">TOTAL PAYMENT</p>
<p><%=@entity.amount%></p>
</div>
<hr>
<%=link_to "Add new transaction", new_entity_path, class:"btn btn-success"%>
</div>

app/views/group/index.html.erb
<%= stylesheet_link_tag 'style' %>
<%=render partial: "shared/navbar", locals: {pagename: @pagename}%>
<div class="categorylist  d-flex flex-column">
<% @groups.each do |group| %>
<%amount = @amounts.filter { |value| value.group_id == group.id }%>
<div class="entity d-flex">
<div class="img-container d-flex">
<%= image_tag url_for(group.icon.variant(resize_to_limit: [100, 100])), class: "logo_photo"%>
</div>
  <div class="entity_box d-flex flex-column">
  <div>
   <%= link_to "#{group.name}",group_path(group.id)%>
   <%if amount.empty?%>
       <p>$0</p>
      <%else%>
      <p>$<%=amount[0].total_amount %></p>
      <%end%>
      </div>
      <p><%=group.created_at.strftime("%d %b %Y")%></p>
  </div>
</div>
<%end %>
<div class= "scan-btn" >
<%=link_to "Add new category", new_group_path %>
<div>
</div>

app/views/group/new.html.erb
<%=render partial: "shared/sub_navbar", locals: {pagename: @pagename}%>
<div class="container-fluid">
<%= form_with model: @group, url: group_index_path , method: :post do |f| %>

<div class="form-group">
  <div class="form-inline mb-3">
     <%= f.label :name, class: "form-label mr-3" do %>
       Name
       <input type="text" name="name" class= "form-control">
     <%end%>
  </div>
  <div class="form-inline mb-3">
     <%= f.label :icon, class: "form-label mr-3" do %>
       Upload icon
       <%= f.file_field :icon %>
     <%end%>
  </div>
<%= f.submit "Add new category", class: "btn btn-primary" %>
<% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

</div>

app/views/group/show.html.erb
<%=render partial: "shared/sub_navbar", locals: {pagename: @pagename}%>
<div class="entity-show d-flex flex-column">
<div class="entity-show-top d-flex">
<div class="img-container d-flex">
<%= image_tag url_for(@group.icon.variant(resize_to_limit: [100, 100])), class: "logo_photo"%>
</div>
<p><%=@group.name%></p>
</div>
<p>Commodi minima excepturi repudiandae velit hic maxime
doloremque. Quaerat provident commodi consectetur veniam similique ad 
earum omnis ipsum saepe, voluptas, hic voluptates pariatur est explicabo 
fugiat, dolorum eligendi quam cupiditate excepturi mollitia maiores labore 
suscipit quas? Nulla, placeat.</p>
<hr>
<%@entities.each do |e|%>
<h1>Transaction <%=e.entity.id%></h1>
<p><%=e.entity.created_at.strftime("%d %b %Y")%></p>
<hr>
<div class="d-flex justify-content-between">
<p class="total-heading">TOTAL PAYMENT</p>
<p><%=e.entity.amount%></p>
</div>
<hr>
<%end%>
<%=link_to "Add new transaction", new_entity_path, class:"btn btn-success"%>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <%= stylesheet_link_tag 'style' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
     <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
  <button class="navbar-toggler ms-3" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand ms-lg-5 ms-md-4 me-sm-3" href="/"><%=pagename%></a>
  <%=image_tag url_for('search.png'), class: "search-icon"%>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%=link_to "Home", group_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=link_to "Sign_out", destroy_user_session_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_signup_navbar.html.erb
     <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
    <%= link_to group_index_path do %>
    <%=image_tag url_for('arrow.png'), class: "search-icon"%>
   <%end%>
  <a class="navbar-brand ms-lg-5 ms-md-4 me-sm-3" href="/"><%=pagename%></a>
  <% if (pagename=="LOGIN")%>
  <%= f.submit "Log in", class:"sign_up_btn" %>
  <% else %>
<%= f.submit "Sign up", class:"sign_up_btn" %>
  <%end%>
</nav>

app/views/shared/_sub_navbar.html.erb
     <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
     <%if defined?(link)%>
      <%= link_to :back do %>
    <%=image_tag url_for('arrow.png'), class: "search-icon"%>
   <%end%>
   <%else%>
    <%= link_to group_index_path do %>
    <%=image_tag url_for('arrow.png'), class: "search-icon"%>
   <%end%>
   <%end%>

  </button>
  <a class="navbar-brand ms-lg-5 ms-md-4 me-sm-3" href="/"><%=pagename%></a>
  <%=image_tag url_for('search.png'), class: "search-icon"%>
</nav>